### PR TITLE
Add secretless OAuth 2 support

### PR DESCRIPTION
**Pull request by TheSpiritXIII**
Partial fix for https://github.com/GoogleCloudPlatform/prometheus-engine/issues/450. This change adds OAuth 2 support but without Client Secret for now. Client Secrets are planned to be represented with Kubernetes secrets in a future PR.

### CODE REVIEW

**Comment by TheSpiritXIII** [comment]
Prometheus does not handle this correctly. I filed a bug here: https://github.com/prometheus/common/issues/528

**Comment by TheSpiritXIII** [comment]
This change is blocked on a new example app image with #732 included.

**Comment by TheSpiritXIII** [comment]
@bwplotka now that we have an example-app image with OAuth 2 fixed, this should be ready for review now. Can you take a look when you have a chance. Thanks!

**Review by bwplotka — APPROVED** [review]
Thanks!

LGTM, sounds like your preference is to merge this before https://github.com/GoogleCloudPlatform/prometheus-engine/pull/776, I am fine equally focusing on the full MVP version as a whole could be a good option too

Let me ask @pintohutch if he is happy with rebasing his e2e PR chain if we merge this 🤗, otherwise good to go!

**Comment by bwplotka** [comment]
Now I am bit surprised we don't use any of "Wait for deployment" etc.. but if you manage to refactor e2e without them, I guess I trust it makes sense 🙈

**Pull request merged**
