### PR TITLE
OperatorConfig compression setting is now also applied for rule-eval. configMap from *Rules CRs [0.9]

### PR DESCRIPTION
**Pull request by bwplotka**
Fixes https://github.com/GoogleCloudPlatform/prometheus-engine/issues/549

### CODE REVIEW

**Comment by bwplotka** [comment]
Done, also tried to extend the e2e test to validate this. Added https://github.com/GoogleCloudPlatform/prometheus-engine/issues/765 idea too.

Testing using SKIP_GCM=false locally...

**Comment by bwplotka** [comment]
I didn't test it yet successfully against GCM, so technically this change is untested. Don't have time to manually test it. 

Tagged v0.9.1-rc.3 without this change so far, up us how we can continue here @pintohutch @TheSpiritXIII

**Review by TheSpiritXIII — APPROVED** [review]
LGTM; I'm okay with patching this into the next release if you're willing to do the work!

**Comment by pintohutch** [comment]
I'm ok merging as well @bwplotka.

Note this should become much easier once #755 is merged and the e2e refactor is readily available. There you can just add a test function or step to the `ruler_test.go` file and run `GOOGLE_APPLICATION_CREDENTIALS=<path-to-file> TEST_RUN=TestRuleEvaluator make e2e` and it should run in a few minutes against GCM.

**Review by pintohutch — APPROVED** [review]

**Comment by bwplotka** [comment]
Ok, I am going to continue my e2e tests, but starting the tag + Louhi process to not waste time. Thanks for reviews!

**Comment by bwplotka** [comment]
... wait, I see a total disaster, blocking this and investigating.

image

**Comment by bwplotka** [comment]
Ok, we would just break & block another release of 0.9 accidently with this PR...

After hardcode debugging (I love kubectl debug now, but it's cryptic):

`kubectl debug -it -n gmp-test-testruleevaluation-gzip-20240112-112556 rule-evaluator-6f9c9d85f7-qc9gt --image=busybox:1.28 --target evaluator`:

image

Yamls are still compressed, because config-reloader does the magic for config files only. Other files are only "watched". We need to add a feature to config-reloader first and make sure we update images once this operator mode is enabled.

Closing for now, let's fix it in 0.10

**Comment by pintohutch** [comment]
Ah good catch - E2E tests would've caught that as well

**Comment by shinebayar-g** [comment]
It looks we're past 0.10 as https://github.com/GoogleCloudPlatform/prometheus-engine/releases/tag/v0.11.0-rc.2 is created?
Is there any chance this getting prioritized? Our GMP has been broken for months.

**Comment by TheSpiritXIII** [comment]
Hi @shinebayar-g we're still in the process of validating the 0.10 release. Our release process involves letting the release candidate soak in the GKE Rapid release channel first before stabilization. We're trying to release 0.10 soon and then put 0.11-rc into the GKE Rapid release channel next.

This project has been deprioritized now that Cloud Alerting supports PromQL alerts. We're recommending users move rules into Cloud Alerting where possible. You may still want some application rules and recording rules (which Cloud Alerting does not support) on the rule-evaluator.

I investigated the effort and it is sizable. Our biggest blocker right now is [Thanos' reloader](https://github.com/thanos-io/thanos/blob/main/pkg/reloader/reloader.go) does not support decompressing directories. This would involve tracking files being added, renamed and removed. To get this merged upstream, this would also have to support symlinks. Since Thanos and we are open source, we're happy to accept contributions and review code in either repository.

Hope that helps!

**Comment by shinebayar-g** [comment]
Thanks for the reply @TheSpiritXIII 

> This project has been deprioritized now that Cloud Alerting supports PromQL alerts.

By this project you mean Google Managed Prometheus as a whole? Or specific component of it?

**Comment by TheSpiritXIII** [comment]
Only the `rule-evaluator` component has been deprioritized for the time being. Google Managed Service for Prometheus is very much alive and we're actively working on it!

**Comment by shinebayar-g** [comment]
> We're recommending users move rules into Cloud Alerting where possible.

By this are you referring to this? https://cloud.google.com/monitoring/promql/promql-in-alerting & https://cloud.google.com/monitoring/promql/promql-migrate?

**Comment by shinebayar-g** [comment]
Okay, we'll follow https://cloud.google.com/stackdriver/docs/managed-prometheus/rules-unmanaged#eval-rules-unmanaged document to deploy self managed rule-evaluator.

> Our biggest blocker right now is [Thanos' reloader](https://github.com/thanos-io/thanos/blob/main/pkg/reloader/reloader.go) does not support decompressing directories.

This is assuming `rules-generated` config map is already compressed. But this isn't possible today. It looks like this PR already contains the necessary code to compress the generated configmap. If this PR is merged I can work on decompressing code on sidecar container side.

**Comment by TheSpiritXIII** [comment]
@shinebayar-g whipped up https://github.com/thanos-io/thanos/pull/7199 real quick. Haven't done much testing on it but hypothetically it should work with this change. If we get that change reviewed and merged upstream, we can try and revive this PR!

In the meanwhile you could try and build this PR yourself. Sadly, we can't currently merge this PR right now because it would be broken.

Thanks for your interest in GMP!

**Comment by shinebayar-g** [comment]
> Sadly, we can't currently merge this PR right now because it would be broken.

Yeah I agree, thanks for the PR. Hope we'll get it soon! 🚀

**Comment by shinebayar-g** [comment]
Thanks for the update @TheSpiritXIII

**Pull request closed without merging**
