### PR TITLE
0.9: Bump module version + vendoring we forgot.

### PR DESCRIPTION
**Pull request by bwplotka**

### CODE REVIEW

**Comment by bwplotka** [comment]
NOTE: I added bug fix straight to branch by accident https://github.com/GoogleCloudPlatform/prometheus-engine/commit/1d0ff29a760b808972f857f6810296976b12f2c0

**Comment by bwplotka** [comment]
We know it's bit broken for now, so maybe that's ok to ignore? 👇🏽 @TheSpiritXIII 🤔 

image

**Comment by bwplotka** [comment]
This however might be a valid error 🤔 

image

**Comment by bwplotka** [comment]
Checking if we fixed this on main: 

image

**Comment by TheSpiritXIII** [comment]
e2e tests are flaky sadly. :(

**Review by TheSpiritXIII — APPROVED** [review]

**Comment by bwplotka** [comment]
@pintohutch pushed fix directly to release branch, despite this PR being up and here and initially suggested some test failures.

**Comment by pintohutch** [comment]
Oh apologies @bwplotka @TheSpiritXIII - I didn't realize this was up. Thanks for tagging - I definitely should've opened a PR instead of pushing to the branch. Had a bit of a brain-fart thinking "it's not `main` so YOLO".

**Pull request closed without merging**
