### PR TITLE
Disable target status reporting by default

### PR DESCRIPTION
**Pull request by pintohutch**
Introduce a field in the OperatorConfig to toggle target status reporting as an opt-in feature.

The motivation for this is to minimize cpu and memory usage of the operator in cases where people don't care to use the feature.

### CODE REVIEW

**Review by TheSpiritXIII — APPROVED** [review]
Look good!

**Comment by lyanco** [comment]
lgtm

**Review by macxamin — APPROVED** [review]
LGTM, should we remove this flag https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/pkg/operator/operator.go#L122

I don't see it being set and it makes the code confusing.

**Comment by pintohutch** [comment]
> 

Good call! Done

**Pull request merged**
