### PR TITLE
gcm/promtest: Added gmp collector.

### PR DESCRIPTION
**Pull request by bwplotka**
Child PR: https://github.com/GoogleCloudPlatform/prometheus-engine/pull/634

### CODE REVIEW

**Comment by bwplotka** [comment]
NOTE: Chained PRs sucks - no tests are ran for them ):

**Comment by TheSpiritXIII** [comment]
Do we want to maintain both collector and export? It sounds like the collector makes the export a bit redundant.

**Comment by bwplotka** [comment]
I am not sure you get the benefit of export yet (: Export gives ability to use local/IDE debugger, 1s-one-click feedback loop when adding new feature/changing export code, and testing export code on every PR CI run.

It's probably overkill to run both in each test, one is enough generally, but for some tests we could run GMP collector as an integration test of Prometheus and export. Perhaps something to add to our fork tests (importing promtest from here)?

**Comment by bwplotka** [comment]
Closing this one, it will be introduced by PRW test suite.

**Pull request closed without merging**
