### PR TITLE
[E2E refactor - 10] move e2e utils to dedicated pkg for future use

### PR DESCRIPTION
**Pull request by pintohutch**
I decided to break out the kind E2E test refactor PR https://github.com/GoogleCloudPlatform/prometheus-engine/pull/738 into smaller, digestible PRs for reviewing.

Note: because of the nature of the change, presubmits (i.e. Github Actions) may fail until the final PR is merged.

This is the tenth (and final!) one, where we move util packages out of `e2e/` to a dedicated library in managed collection for future use.

### CODE REVIEW

**Review by bwplotka — CHANGES_REQUESTED** [review]
Thanks! So many utils!

image

What exactly future use you have in mind? Will we ever use those outside of e2e test? If not I would keep them in e2e honestly, otherwise it suggests it should be used in prod code.

The util name also means nothing, it would epic to at least have only one "util" e.g. `e2e/kubeutil/...` and `e2e/operatorutil/<files without util suffix>` unless we literally import those from outside of e2e package. (maybe I am missing something).

BTW I am surprised you didn't have to change any caller references? Does it mean those are not used? The let's remove for now (we can always bring those back via git).

**Review by bwplotka — APPROVED** [review]
LGTM, I would say let's work with @TheSpiritXIII to create a dedicated repo (library) for those utils, they are super useful, just not at the moment. 

Let's figure the name of it and maintain there, seriously (:

**Comment by TheSpiritXIII** [comment]
Let's nuke it. I know where to look if we ever need these utilities back.

**Review by TheSpiritXIII — APPROVED** [review]

**Comment by pintohutch** [comment]
Thanks all!

**Pull request merged**
